#!/usr/bin/env bash
script_afp=$(realpath "${BASH_SOURCE[0]}")

# input guards

  setup_must_be="developer/tool/setup"
  if [ "$ENV" != "$env_must_be" ]; then
    echo "$(script_fp):: error: must be run in the $env_must_be environment"
    exit 1
  fi

set -e
set -x

  cd "$REPO_HOME"/developer || exit 1
  # /bin/make -f tool/makefile $@

  mkdir -p scratchpad/authored
  cp authored/HTTP_server.js scratchpad/authored/
  cp authored/port_forwarder scratchpad/authored/
  cp authored/port_forwarder_CLI scratchpad/authored/
  cp authored/permission_RT scratchpad/authored/
  cp authored/permission_UPG scratchpad/authored/

set +x
echo "$(script_fn) done."
